####################################################
# 1ª stage: build usando Maven
####################################################
FROM maven:3.8.8-eclipse-temurin-17-alpine AS build

WORKDIR /build
COPY pom.xml .
COPY src ./src

# gera o JAR (skip tests para acelerar; remova -DskipTests se quiser rodar)
RUN mvn clean package -DskipTests

####################################################
# 2ª stage: runtime com JRE
####################################################
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app
# Cria um usuário comum chamado default evitando privilégios desnecessários
RUN addgroup -S default && adduser -S default -G default

# copia apenas o JAR gerado na etapa anterior
COPY --from=build /build/target/gestao_vagas-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
USER default
ENTRYPOINT ["java", "-jar", "app.jar"]
